
export const defaultcodeLists = [
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'BRCA1 Gene Analysis Report', code: 'LPC100' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'BRCA2 Gene Analysis Report', code: 'LPC101' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MLH1 Gene Sequencing Analysis Report', code: 'LPC117' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MSH2 Gene Sequencing Analysis Report', code: 'LPC118' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'RUNX1 Gene Sequencing Analysis Report', code: 'LPC194' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'LDLR Gene Sequencing Analysis Report', code: 'LPE115' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'FBN1 Gene Sequencing Analysis Report', code: 'LPE141' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MYD88 Gene Sequencing Analysis Report', code: 'LPE156' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'VHL Gene Sequencing Analysis Report', code: 'LPE194' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PARK2 Gene Sequencing Analysis Report', code: 'LPE221' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'CYP21A2 Gene Sequencing Analysis Report', code: 'LPE227' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TGFBI Gene Sequencing Analysis Report', code: 'LPE229' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'FGFR3 Gene Sequencing Analysis Report', code: 'LPE231' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'ELA2 Gene Sequencing Analysis Report', code: 'LPE233' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'SCN5A Gene Sequencing Analysis Report', code: 'LPE236' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'KCNH2 Gene Sequencing Analysis Report', code: 'LPE237' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'KCNQ1 Gene Sequencing Analysis Report', code: 'LPE238' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'NF2 Gene Sequencing Analysis Report', code: 'LPE241' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'NOTCH3 Gene Sequencing Analysis Report', code: 'LPE243' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'NF1 Gene Sequencing Analysis Report', code: 'LPE245' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'BTK Gene Sequencing Analysis Report', code: 'LPE247' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'CDH1 Gene Sequencing Analysis Report', code: 'LPE249' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'STK11 Gene Sequencing Analysis Report', code: 'LPE251' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TSC2 Gene Sequencing Analysis Report', code: 'LPE258' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'APC Gene Sequencing Analysis Report', code: 'LPE262' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PTPN11 Gene Sequencing Analysis Report', code: 'LPE267' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'WAS Gene Sequencing Analysis Report', code: 'LPE272' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PKD 1 Gene Sequencing Analysis Report', code: 'LPE275' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PKD 2 Gene Sequencing Analysis Report', code: 'LPE276' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'FGFR2 Gene Sequencing Analysis Report', code: 'LPE280' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TSC1 Gene Sequencing Analysis Report', code: 'LPE282' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PAX6 Gene Sequencing Analysis Report', code: 'LPE285' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'RET Gene Sequencing Analysis Report', code: 'LPE287' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'NRAS Gene Sequencing Analysis Report', code: 'LPE289' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'KRAS Gene Sequencing Analysis Report', code: 'LPE290' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TP53 Gene Sequencing Analysis Report', code: 'LPE295' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'LHON Gene Sequencing Analysis Report', code: 'LPE302' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'HNF1A Gene Sequencing Analysis Report', code: 'LPE306' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PTEN Gene Sequencing Analysis Report', code: 'LPE308' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MEN1 Gene Sequencing Analysis Report', code: 'LPE310' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PRF1 Gene Sequencing Analysis Report', code: 'LPE313' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'UNC13D Gene Sequencing Analysis Report', code: 'LPE314' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'FANCA Gene Sequencing Analysis Report', code: 'LPE316' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'ATP7B Gene Sequencing Analysis Report', code: 'LPE320' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MAPT Gene Sequencing Analysis Report', code: 'LPE334' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'RPS19 Gene Sequencing Analysis Report', code: 'LPE337' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'CFTR Gene Sequencing Analysis Report', code: 'LPE340' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'DHCR7 Gene Sequencing Analysis Report', code: 'LPE341' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'STAR Gene Sequencing Analysis Report', code: 'LPE342' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MUTYH Gene Sequencing Analysis Report', code: 'LPE343' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'HBB Gene Sequencing Analysis Report', code: 'LPE349' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'SPTB Gene Sequencing Analysis Report', code: 'LPE352' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'COL1A1 Gene Sequencing Analysis Report', code: 'LPE354' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'COL1A2 Gene Sequencing Analysis Report', code: 'LPE356' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'ASXL1 Gene Sequencing Analysis Report', code: 'LPE358' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'DNMT3A Gene Sequencing Analysis Report', code: 'LPE360' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'SF3B1 Gene Sequencing Analysis Report', code: 'LPE362' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TET2 Gene Sequencing Analysis Report', code: 'LPE364' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'DNAH5, DNAI1 Gene Sequencing Analysis Report', code: 'LPE366' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'THRB Gene Sequencing Analysis Report', code: 'LPE368' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'JAK3 Gene Sequencing Analysis Report', code: 'LPE371' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TGFBR1 Gene Sequencing Analysis Report', code: 'LPE374' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TGFBR2 Gene Sequencing Analysis Report', code: 'LPE375' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'UGT1A1 Gene Sequencing Analysis Report', code: 'LPE378' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PANK2 Gene Sequencing Analysis Report', code: 'LPE379' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'G6PD Gene Sequencing Analysis Report', code: 'LPE384' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'HBA1 Gene Sequencing Analysis Report', code: 'LPE391' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'HBA2 Gene Sequencing Analysis Report', code: 'LPE392' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'CSF3R Gene Sequencing Analysis Report', code: 'LPE410' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'FLCN Gene Sequencing Analysis Report', code: 'LPE412' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PKHD1 Gene Sequencing Analysis Report', code: 'LPE414' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'HAX1 Gene Sequencing Analysis Report', code: 'LPE418' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'DMD Gene Sequencing Analysis Report', code: 'LPE420' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'MLL2 Gene Sequencing Analysis Report', code: 'LPE428' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'IKBKG Gene Sequencing Analysis Report', code: 'LPE431' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'PRRT2 Gene Sequencing Analysis Report', code: 'LPE433' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'EPOR Gene Sequencing Analysis Report', code: 'LPE436' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'FANCG Gene Sequencing Analysis Report', code: 'LPE457' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'NSD1 Gene Sequencing Analysis Report', code: 'LPE460' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'CHD7 Gene Sequencing Analysis Report', code: 'LPE462' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TTR Gene Sequencing Analysis Report', code: 'LPE469' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'GNAS Gene Sequencing Analysis Report', code: 'LPE477' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'TGFBI Exon4,11,12,14 Sequencing Analysis Report', code: 'LPE481' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'AVP Gene Sequencing Analysis Report', code: 'LPE482' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'CFH Gene Sequencing Analysis Report', code: 'LPE494' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'SEQ', report: 'SLC12A3 Gene Sequencing Analysis Report', code: 'LPE495' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'DMD Gene MLPA Analysis Report', code: 'LPE232' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: '미세결실증후군 MLPA Analysis Report', code: 'LPE294' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'SMN1/2 Gene MLPA Analysis Report', code: 'LPE322' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'CYP21A2 Gene MLPA Analysis Report', code: 'LPE332' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'HBA1/2 Gene MLPA Analysis Report', code: 'LPE351' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'VHL Gene MLPA Analysis Report', code: 'LPE369' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'PMP22 Gene MLPA Analysis Report', code: 'LPE377' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'MLPA', report: 'PARK2 Gene MLPA Analysis Report', code: 'LPE464' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '근긴장이상 질환 [NGS]', code: 'LPE548' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: 'Long QT panel [NGS]', code: 'LPE439' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 용혈성 빈혈 [NGS]', code: 'LPE452' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '판코니빈혈 [NGS]', code: 'LPE453' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '골수부전증후군 [NGS]', code: 'LPE454' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '선천성 혈소판 감소증 [NGS]', code: 'LPE455' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '선천성 백혈구 감소증 [NGS]', code: 'LPE456' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 난청 [NGS]', code: 'LPE488' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '선천성 면역결핍증 [NGS]', code: 'LPE489' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 대동맥질환 [NGS]', code: 'LPE490' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 암 [NGS]', code: 'LPE497' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '혈전성 미세혈관병증 [NGS]', code: 'LPE498' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '다낭성 신장질환 [NGS]', code: 'LPE499' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 신장질환 [NGS]', code: 'LPE517' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 심근병증 [NGS]', code: 'LPE518' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 피부질환 [NGS]', code: 'LPE519' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 근신경계 질환 [NGS]', code: 'LPE520' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 신경병증 [NGS]', code: 'LPE521' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 골형성이상 질환 [NGS]', code: 'LPE522' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 발달지연(DD/ASD) [NGS]', code: 'LPE523' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 저신장증 [NGS]', code: 'LPE524' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 결합조직 질환 [NGS]', code: 'LPE525' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 근육퇴행위축 질환 [NGS]', code: 'LPE526' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 근육병증 [NGS]', code: 'LPE527' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '샤르코 마리 투스병 [NGS]', code: 'LPE528' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 운동실조증 [NGS]', code: 'LPE529' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 강직하반신마비 [NGS]', code: 'LPE530' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 강직하반신마비 [NGS]', code: 'LPE531' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: 'Ras질병(Rasopahy) [NGS]', code: 'LPE532' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 내분비질환 [NGS]', code: 'LPE533' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 응고병증 [NGS]', code: 'LPE534' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 뇌전증 [NGS]', code: 'LPE535' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '알츠하이머병  [NGS]', code: 'LPE536' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '치매 [NGS]', code: 'LPE537' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '파킨슨병 [NGS]', code: 'LPE538' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 망막병증 [NGS]', code: 'LPE539' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 당뇨 [NGS]', code: 'LPE540' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '라이소좀 축적 질환 [NGS]', code: 'LPE541' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '선천성 대사이상 [NGS]', code: 'LPE542' },
  { target: '', specimen: '', analyzedgene: '', method: '', comment1: '', comment2: '', type: 'Genetic', report: '유전성 망막색소병증 [NGS]', code: 'LPE543' },
];
